export const persons = [
    {
      p_name: "Amit Datta",
      p_location: "Gulshan",
      p_year: "2022",
      p_hire: "15",
      p_verify: "25%",
      p_image: "./user2.png",
      p_icon:"./v25.png",
      id: 1,
    },
    {
      p_name: "Anik Datta",
      p_location: "Buet Campus",
      p_year: "2023",
      p_hire: "10",
      p_verify: "50%",
      p_image: "./user1.png",
      p_icon:"./v50.png",
      id: 2,
    },
    {
      p_name: "Irfan Ali",
      p_location: "Rampura",
      p_year: "2023",
      p_hire: "10",
      p_verify: "50%",
      p_image: "./user1.png",
      p_icon:"./v50.png",
      id: 3,
    },
    {
      p_name: "Shuvo",
      p_location: "Uttor Badda",
      p_year: "2022",
      p_hire: "5",
      p_verify: "100%",
      p_image: "./user1.png",
      p_icon:"./v100.png",
      id: 4,
    },
    {
      p_name: "Salam",
      p_location: "Airport",
      p_year: "2023",
      p_hire: "20",
      p_verify: "50",
      p_image: "./user1.png",
      p_icon:"./v50.png",
      id: 5,
    },
  ];

  